const colors={gate:'#174a7c'};const markerIcon=(color)=>L.divIcon({className:'port-marker-wrap',html:`<span class="port-marker" style="background:${color}"></span>`,iconSize:[22,22],iconAnchor:[11,11]});
const driverGates=[{id:'sinseondae',name:'BPT 신선대',point:[35.1125,129.0910]},{id:'gamman',name:'BPT 감만',point:[35.1036,129.0978]},{id:'pnit',name:'PNIT',point:[35.0735,128.8300]},{id:'pnc',name:'PNC',point:[35.076,128.812]},{id:'hjnc',name:'HJNC',point:[35.075,128.798]},{id:'hpnt',name:'HPNT',point:[35.075,128.789]},{id:'bnct',name:'BNCT',point:[35.076,128.781]},{id:'bct',name:'BCT',point:[35.077,128.772]},{id:'dgt',name:'DGT',point:[35.083,128.759]}];
function baseMap(id,interactive=true){const map=L.map(id,{zoomControl:false,scrollWheelZoom:interactive}).setView([35.09,128.93],10);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);driverGates.forEach(g=>L.marker(g.point,{icon:markerIcon(colors.gate)}).addTo(map).bindTooltip(g.name,{permanent:true,direction:'top'}));return map;}
const driverMap=baseMap('driverMap'),routeMap=baseMap('routeMap',false),navigationMap=baseMap('navigationMap',false);let routeLines=[],navigationLines=[];
function clear(lines){lines.forEach(line=>line.remove());return [];}
function trafficPath(map,points,isNavigation=false){const lines=clear(isNavigation?navigationLines:routeLines);const palette=['#28a86b','#f4ad32','#eb4b4b'];for(let i=0;i<points.length-1;i++){const color=palette[Math.min(i,palette.length-1)];lines.push(L.polyline([points[i],points[i+1]],{color,weight:isNavigation?9:6,opacity:.95}).addTo(map));}if(isNavigation)navigationLines=lines;else routeLines=lines;const group=L.featureGroup(lines);map.fitBounds(group.getBounds(),{padding:[28,28]});}
window.refreshRouteMap=()=>routeMap.invalidateSize();window.updateDriverMapPosition=(lat,lng)=>{L.marker([lat,lng],{icon:markerIcon('#1576d2')}).addTo(driverMap);driverMap.flyTo([lat,lng],12);};
window.drawRecommendedRoute=(vertices)=>{if(!vertices?.length)return;const start=[vertices[1],vertices[0]],end=[vertices[vertices.length-1],vertices[vertices.length-2]],mid=[(start[0]+end[0])/2,(start[1]+end[1])/2];trafficPath(routeMap,[start,mid,end]);};
window.showNavigationGuide=()=>{const gate=driverGates.find(g=>g.id===window.bestGateId)||driverGates[0],e=window.gateEstimates?.[gate.id],o=document.getElementById('originInput').value.split(',').map(Number);document.getElementById('navigationGateName').textContent=`${gate.name}로 이동하세요`;document.getElementById('navigationSummary').textContent=e?`이동 ${e.duration}분 + 게이트 대기 ${e.wait}분 = 총 ${e.total}분`:'STEP 2에서 경로를 계산하세요.';document.getElementById('navigationInstruction').textContent='초록은 원활, 노랑은 주의, 빨강은 혼잡 구간입니다.';navigationMap.invalidateSize();if(o.length===2){const start=[o[1],o[0]],mid=[(start[0]+gate.point[0])/2,(start[1]+gate.point[1])/2];trafficPath(navigationMap,[start,mid,gate.point],true);}};
driverMap.on('click',e=>window.setAppOrigin?.(e.latlng.lat,e.latlng.lng,'지도를 눌러 현재 위치를 설정했습니다.'));
