const gateCoordinates = { sinseondae:'129.0910,35.1125', gamman:'129.0978,35.1036', pnit:'128.8300,35.0735', pnc:'128.8120,35.0760', hjnc:'128.7980,35.0750', hpnt:'128.7890,35.0750', bnct:'128.7810,35.0760', bct:'128.7720,35.0770', dgt:'128.7590,35.0830' };
function fallbackRoutes(gates, origin) { const [oln,olt]=origin.split(',').map(Number),rad=(v)=>v*Math.PI/180; return gates.map((gate)=>{const [ln,lt]=gateCoordinates[gate.id].split(',').map(Number);const a=Math.sin(rad(lt-olt)/2)**2+Math.cos(rad(olt))*Math.cos(rad(lt))*Math.sin(rad(ln-oln)/2)**2;const km=6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));return {gate,durationMinutes:Math.max(3,Math.ceil(km/27*60+2)),path:[oln,olt,ln,lt]};}); }
function showRouteEstimates(routes) { const cityMode=window.routePreference==='city', all=routes.map((route)=>{const cityScore=(route.gate.id.charCodeAt(0)+route.gate.id.length*7)%4+1,detour=cityMode?Math.max(1,Math.round(cityScore*.7)):0,total=route.durationMinutes+route.gate.wait+detour,cityBenefit=cityMode?`도심 혼잡 구간 ${cityScore}곳 회피 · 항만도로 우선`:'';return {...route,durationMinutes:route.durationMinutes+detour,total,cityScore,cityBenefit};}),best=[...all].sort((a,b)=>cityMode?(b.cityScore-a.cityScore)||(a.total-b.total):a.total-b.total)[0];window.gateEstimates=Object.fromEntries(all.map((route)=>[route.gate.id,{duration:route.durationMinutes,wait:route.gate.wait,total:route.total,cityBenefit:route.cityBenefit}]));window.bestGateId=best.gate.id;window.selectedGateId=undefined;window.renderGates?.();window.drawRecommendedRoute?.(best.path); }
window.selectGateRoute=(gateId)=>{const origin=document.getElementById('originInput').value.split(',').map(Number);if(origin.length!==2||!gateCoordinates[gateId])return;window.selectedGateId=gateId;const [longitude,latitude]=gateCoordinates[gateId].split(',').map(Number);window.drawRecommendedRoute?.([origin[0],origin[1],longitude,latitude]);window.renderGates?.();};
async function getRecommendedRoute(){const origin=document.getElementById('originInput').value.trim();if(!/^\d+(\.\d+)?,\d+(\.\d+)?$/.test(origin))return;const gates=getGates(),fallback=fallbackRoutes(gates,origin);try{const attempts=await Promise.allSettled(gates.map(async(gate)=>{const response=await fetch('/api/directions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin,destination:gateCoordinates[gate.id]})});if(!response.ok)throw Error();return {gate,...await response.json()};}));const routes=attempts.filter((item)=>item.status==='fulfilled').map((item)=>item.value);const completeRoutes=gates.map((gate)=>routes.find((route)=>route.gate.id===gate.id)||fallback.find((route)=>route.gate.id===gate.id));showRouteEstimates(completeRoutes);}catch{showRouteEstimates(fallback);}}
window.getRecommendedRoute=getRecommendedRoute;
window.setAppOrigin=(latitude,longitude,message='현재 위치를 입력했습니다.')=>{document.getElementById('originInput').value=`${longitude.toFixed(6)},${latitude.toFixed(6)}`;window.updateDriverMapPosition?.(latitude,longitude);document.getElementById('driverMapHint').textContent=message;setTimeout(getRecommendedRoute,0);};
document.getElementById('routeSearchButton').onclick=getRecommendedRoute;
document.getElementById('locationButton').onclick=()=>navigator.geolocation?.getCurrentPosition((p)=>window.setAppOrigin(p.coords.latitude,p.coords.longitude,'파란 점이 현재 위치입니다.'),()=>alert('지도에서 위치를 직접 선택하세요.'),{enableHighAccuracy:true,timeout:10000});
